sensor:
  - platform: debug
    free:
      name: "Heap Free"
    psram:
      name: "PSRAM Free"
    loop_time:
      name: "Loop Time"
    cpu_frequency:
      name: "CPU Frequency"
    block:
      name: "Heap Max Block"
