esphome:
  name: esp32_c3_super_mini
  friendly_name: ESP32 C3 SuperMini
  name_add_mac_suffix: True

esp32:
  board: esp32dev
  variant: esp32c3 
  early_pin_init: false
  framework:
    type: esp-idf

packages: 
  esp32_package:
    url: https://github.com/MorganMLGman/ESPHomeBaseFiles
    files:
      - base.yaml
      - ESP32/diagnostic.yaml
      - ESP32/web_server.yaml
    ref: master
    refresh: 1d