substitutions: 
  ap_password: "123456789"

logger:
  level: DEBUG

safe_mode:

wifi:
  reboot_timeout: 10min
  ap:
    password: ${ap_password}
    
api:
  reboot_timeout: 10min

button:
  - platform: factory_reset
    id: factory_reset_button_0
    name: Factory Reset
