logger:
  level: DEBUG

safe_mode:

wifi:
  reboot_timeout: 10min
  ap:

captive_portal:

api:
  reboot_timeout: 10min

packages:
  base_diagnostic: github://MorganMLGman/ESPHomeBaseFiles/base_diagnostic.yaml