substitutions: 
  ap_password: "123456789"

logger:
  level: DEBUG

safe_mode:

wifi:
  reboot_timeout: 10min
  ap:
    password: ${ap_password}

improv_serial:

api:
  reboot_timeout: 10min

packages:
  base_diagnostic: 
    url: https://github.com/MorganMLGman/ESPHomeBaseFiles
    files:
      - base_diagnostic.yaml
    ref: master
    refresh: 1d
