esphome:
  name: esp01_1m
  friendly_name: ESP01 1M
  name_add_mac_suffix: True

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false
  framework:
    version: recommended

packages: 
  esp8266_package:
    url: https://github.com/MorganMLGman/ESPHomeBaseFiles
    files:
      - base.yaml
      - ESP8266/diagnostic.yaml
      - ESP8266/web_server.yaml
    ref: master
    refresh: 1d