esphome:
  name: esp01_1m
  friendly_name: ESP01 1M
  name_add_mac_suffix: True

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false
  framework:
    version: recommended

packages: 
  base:       !include ../base.yaml
  diagnostic: !include diagnostic.yaml
  web_server: !include web_server.yaml