esphome:
  name: esp01_1m
  friendly_name: ESP01 1M
  name_add_mac_suffix: True

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false
  framework:
    version: recommended

logger:
  level: DEBUG

safe_mode:

wifi:
  reboot_timeout: 10min
  ap:

captive_portal:

api:
  reboot_timeout: 10min

web_server:
  port: 80
  local: false
  ota: true
  include_internal: True
  version: 2

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: ESPHome Version
    entity_category: "diagnostic"

  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: "diagnostic"
    ssid:
      name: WiFi SSID
      entity_category: "diagnostic"
    bssid:
      name: WiFi BSSID
      entity_category: "diagnostic"

binary_sensor:
  - platform: status
    id: esp_status
    name: Status
    device_class: connectivity

sensor:
  - platform: wifi_signal
    name: WiFi Signal dB
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: WiFi Signal Percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    update_interval: 60s
    accuracy_decimals: 0
    icon: mdi:clock-outline
    entity_category: "diagnostic"

button:
  - platform: restart
    name: Restart
  
  - platform: safe_mode
    name: Safe Mode

  - platform: factory_reset
    id: factory_reset_button
    name: Factory Reset