esphome:
  name: esp01_1m
  friendly_name: ESP01 1M
  name_add_mac_suffix: True

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false
  framework:
    version: recommended

packages: 
  base:       github://MorganMLGman/ESPHomeBaseFiles/base.yaml
  diagnostic: github://MorganMLGman/ESPHomeBaseFiles/ESP8266/diagnostic.yaml
  web_server: github://MorganMLGman/ESPHomeBaseFiles/ESP8266/web_server.yaml